version: "3.3"

services:
  customrooms:
    image: customrooms
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./database:/Bot/database
    environment:
      - TOKEN=<your token>
